#!/bin/bash
trap '' 2  # ignore control + c
echo "=================================================================================="
echo "                    sZZZZ.          ,I,"           
echo "                   ZZ. ..sZ:    .Zss?.7s7.   "    
echo "                  .s.     ..  .Zs:     .s.   "    
echo "                  IZ.        Zs         s~   "   
echo "                  IZ       7ZI         .s:   "    
echo "                  .s.    .Zs            s    "    
echo "                  .sZZZsZsssZZsssss,         "    
echo "              sZZsZsZ...ZZ   ......?Zssss7   "    
echo "           .Zs~.    s.:s               ..?sZZ."    
echo "          +s.       Zss:     .     Zs.     .,ss."  
echo "          ZZ        .s?    sssss   .s=        ?s. "
echo "          .ss       sZs    7ssss    ,s         Z: "
echo "            Zss    ZZ.Zs.   ...      ZZ      .ss. "
echo "             .=.  +s.  Zs             Z.  .7Zs? "  
echo "                  s=    sZ            Zs  .~.   "  
echo "                 =Z      ss           ~s         " 
echo "                 ZZ      .sZ.         .s.         "
echo "                 s,       .ZZ.         s+         "
echo "                 s.         ?$+        Z?         "
echo "                 sZ     ss7  .ss      .Z.         "
echo "                  ssZssss.    .,ss,   Zs     "
toilet Program13 ; toilet For Dummies
echo  "================================================================================="
echo  "Make a selection from this list and enter the op command while on the main menu."
echo "=================================================================================="
echo "Enter drift to view all images on network (May not exit properly):"
  echo "Enter ipscan to scan network for IP's:"
  echo "Enter wipass to view current Wifi with password:"
  echo "Enter starwars to watch StarWars:"
  echo "Enter 99bot to hear terminal sing 99bottles:"
  echo "Enter comcom to view a list of most used commands:"
  echo "Enter funfact for a fun fact:"
  echo "Enter learn to learn a little:"
  echo "Enter ffh to view Firefox History:"
  echo "Enter fff to view Firefox Form data:"
  echo "Enter lib13 to open library:"
  echo "Enter program13 to view our website:"
  echo "Enter geoip to get Geographical Info about IP Address:"
  echo "Enter google to search Google"
  echo "Enter def to look up the definition of a word:"
  echo "Enter webinfo to look up info about a website WARNING:MAY NOT BE LEGAL IN YOUR AREA:"
  echo "Enter pipl to search Pipl.com:"
  echo "Enter yp to search YellowPages:"
  echo "Enter wolf to search WolframAlpha:"
  echo "Enter 10d for 10Digit search:"
  echo "Enter ddg to search DuckDuckGo:"
  echo "Enter allpics to get all images from a website:"
  echo "Enter weather to get the weather in your area:"
  echo "Enter nmap to perform nmap scan of host:"
  echo "Enter moon to get phases of the moon:"
  echo "Enter discord to open our Discord channel:"
  echo "Enter cfc For CaseFile Creator:"
  echo "Enter cfadd to add info to an existing Casefile:"
  echo "Enter cfread to read existing Casefile:"
  echo "Enter cflist to list all Casefiles in Dir:"
  echo "Enter mug to search for arrest records online:"
  echo "Enter smtg to search Magic: The Gathering Rules and Regulations: "
  echo "Enter allmtg to view entire Rules and Regulations for M:TG"
  echo "You may watch movies by typing Hulu, Netflix or Prime: "
  echo "Enter mtgadd to add cards to Magic collection."
  echo "Enter allmtgc to see all Magic: The Gathering Cards."
  echo "Enter mtgc to search for a Magic: The Gathering card."
  echo "Enter myip to get your IP address."
  echo "Enter download to download a file from a website."
  echo "Enter fbd to search the Facebook Directory."
  echo "Enter hide-me to start TOR and open Firefox."
  echo "Enter journal to add a journal entry."
  echo "Enter readjournal to read a journal entry."
  echo "Enter randjourn to add a random journal entry."
  echo "Enter readrand to read a random journal entry."
  echo "Enter journalbs to view the journal bookshelf."
  echo "Enter 13books to write a new book."
  echo "Enter read13 to read 13Books."
  echo "Enter ap13 to add too a 13Book."
  echo "Enter 13bs to see the 13Books bookshelf."
  echo "There are also a few easter eggs :)"
  echo "Enter q to quit q:"
  echo "Enter back to go back to main menu:"
read answer  # create variable to retains the answer
case "$answer" in
   back)./p13.sh ;;
esac
  echo -e "Hit the <return> key to continue.. c"
  read input
